PUT http://127.0.0.1:8000 HTTP/1.1
Content-Type: application/json

{
    "advertisement":{"id":1},
    "content":"Test content",
    "helpful_review_votes":0,
    "id":2,
    "is_deleted":false,
    "stars":5,
    "title":"Test review updated",
    "user":{"id":1,"total_helpful_review_votes":42,"username":"Test user"},
    "create_date": "2022-12-16",
    "modification_date": "2022-12-16",
    "deletion_date": "2022-12-16"
}